import json
from dotenv import load_dotenv, find_dotenv
from typing import List
from pydantic import BaseModel, Field
from langchain.agents import create_agent
from langchain.tools import tool
from langchain_core.messages import HumanMessage, SystemMessage
from langchain_ollama import ChatOllama
from langchain_tavily import TavilySearch
# Load environment variables
load_dotenv(find_dotenv())



class Source(BaseModel):
    """Schema for a source used by the agent."""
    url: str = Field( description="The URL of the source")

class AgentResponse(BaseModel):
    """Schema for agent response with answer and sources."""
    answer: str = Field( description="The final answer generated by the agent")
    sources: List[Source] = Field( description="A list of sources used by the agent to generate the answer")

def main():
    # Define the LLM, tools, and system prompt within the main function
    # for better encapsulation and clarity.
    llm = ChatOllama(temperature=0, model="qwen2.5:14b")
    tools = [TavilySearch()]
    system_prompt = (
        "You are a helpful assistant that finds job postings. You have access to a search tool. "
        "After the search tool is called, its results will appear as a 'Tool Message' containing a list of search results. "
        "Your final response MUST be a JSON object that strictly conforms to the 'AgentResponse' schema. "
        "Use the content from the search results to write a summary for the 'answer' field. "
        "Extract the 'url' from each search result to populate the 'sources' list."
    )

    # Create the agent with the explicit instructions.
    agent = create_agent(model=llm, tools=tools, response_format=AgentResponse, system_prompt=system_prompt)

    query = "search for 3 job psoting for an ai enginerer using langchain in arlington, Texas"
    result = agent.invoke({"messages": [SystemMessage(content=system_prompt), HumanMessage(content=query)]})

    print("\n=== Conversation (qwen2.5:14b) ===\n")
    for i, msg in enumerate(result["messages"]):
        role = getattr(msg, "type", None) or getattr(msg, "role", None) or type(msg).__name__
        print(f"--- Message {i} ({role.upper()}) ---")
        if hasattr(msg, "content") and msg.content:
            print("Content:")
            print(getattr(msg, "content"))
        
        # Print the structured tool calls where AgentResponse lives!
        if hasattr(msg, "tool_calls") and msg.tool_calls:
            print("Tool Calls:")
            print(json.dumps(msg.tool_calls, indent=2))
        print("-" * 50 + "\n")

    # Extract the structured output from the agent's tool calls
    parsed_data = None
    if "structured_response" in result:
        parsed_data = result["structured_response"]
    else:
        # Check the final message for a tool call matching our schema
        final_message = result["messages"][-1]
        if hasattr(final_message, "tool_calls") and final_message.tool_calls:
            for tool_call in final_message.tool_calls:
                if tool_call["name"] == "AgentResponse":
                    parsed_data = AgentResponse(**tool_call["args"])
                    break

        # Fallback: Sometimes local models output the JSON directly in the content string
        if not parsed_data and hasattr(final_message, "content") and final_message.content:
            try:
                parsed_json = json.loads(final_message.content)
                parsed_data = AgentResponse(**parsed_json)
            except Exception:
                pass
        
    if parsed_data:
        print("\n=== Parsed AgentResponse ===")
        print("🎯 The Answer:", parsed_data.answer)
        print("\n🔗 The Sources:")
        for idx, source in enumerate(parsed_data.sources, 1):
            print(f"  {idx}. {source.url}")
    else:
        print("\n❌ Could not extract structured response. Check the raw tool_calls output above.")
if __name__ == '__main__':
    main()
